### ISSUE TITLE
HTMLIFrameElement is missing contentWindow

### ISSUE THREAD

**Issue by niloc132** [google/elemental2#16]
Extern files in closure correctly define the other iframe properties in `w3c_dom2.js`, but this was not added until html5 apparently, see https://www.w3.org/TR/2000/CR-DOM-Level-2-20000510/html.html#ID-67133006 where it is missing, reflecting closure externs.

However, the html5 spec does include it - https://www.w3.org/TR/2011/WD-html5-20110113/the-iframe-element.html, and I have yet to find an html IDL made anywhere in the last several years that fails to include it. Is there a reason that closure externs seem so inconsistent and out of date with the matching spec/idl files? Why is elemental2 not built from idl files instead, so it can be up to date if closure is unable to stay current?

Without this, there is no clear way to call postMessage, etc.

**Comment by niloc132** [comment]
When working around this, a `Js.uncheckedCast` must be used, since the returned Window is a `Window`, but not the page's `Window`, so the `instanceof` fails.

As with the Edge bug around `Location`, this will undoubtedly cause more problems down the road - consider a `List<Window>` so someone can keep track of objects they can post messages to, either iframes or popups (or shared windows). Any time you typecheck the items coming out of that list, they will be the wrong type.

Alternatively, since Window itself is missing `postMessage` anyway (see #17...), it might make more sense for a user to just make their own `@JsType(name="Object") with `postMessage` defined on it, and cast to that.

**Comment by jDramaix** [comment]
> Is there a reason that closure externs seem so inconsistent and out of date with the matching spec/idl files? 
externs are not "so inconsistent". I'm a bit tired of your innuendos. Externs are maintained and used by thousand of js engineer and are closer to the reality than spec/idl files.
If something is missing, just add it like other people do.

>  Why is elemental2 not built from idl files instead, so it can be up to date if closure is unable to stay current?
We tried this path first but idls are not convienient as input files:
- IDL files are not stricly following IDL grammar and parsing need to be very lenient
- Closure type system is richer that IDL and closer to java. In IDL file you cannot define a parameterized type for example.
- IDLs are for api provided by the browser. You don't have idl for api provided by js engine
- One of our most important requirement: we do want elemental2 to be compatible with j2cl. At some point, we need to pass extern files as input of the compilation and elemental2 needs to be in sync with the extern files used by the js compiler.
- ...

Elemental2 is not an official gwtproject.org product. It's a library that we use internally and we think it's worth to make it available for opensource community. If you think it doesn't fit your needs feel free to create your own version or use something else.

**Comment by niloc132** [comment]
I don't meant to accuse, just trying to get to usable, and we're far from that (and late releases, etc), so frustration is building with everyone I know who is trying to use elemental2. I'm also still unclear about _where_ I should be providing fixes - the distinction hasn't been made about when a diff is added in this repo vs upstreaming work to closure.

I don't want to give up on this, but elemental2 is a struggle, and isn't getting better. Give us the power to help you, and we will! Working builds, builds that generate gwt2 compatible jars, etc. 

Thanks for the clarification on idl vs externs.

**Comment by niloc132** [comment]
Looks like S.O.P. from the other recently fixed issues it to make a pull request to upstream closure-compiler, i'll get that started here.

**Comment by jDramaix** [comment]
Fixed internally. Should be imported in https://github.com/google/closure-compiler very soon. Will be part of the RC1

**Comment by ainslec** [comment]
Hi,

I'm using RC1, and it seems that I can't find the "document" property on the Window class. Am I doing this wrong or was the issue not fixed in time for RC1?

Chris

**Comment by jDramaix** [comment]
This issue is about adding the field contentWindow to HTMLIFrameElement.
If document needs to be present in the Window object, please open a new bug so that we can discuss there.

thanks,
